export { default as NavBar } from './NavBar';
export { default as LandingPage } from './LandingPage';
export { default as FeaturedProducts } from './FeaturedProducts';
export { default as SalePage } from './SalePage';
export { default as LovedProducts } from './LovedProducts';
export { default as Reviews } from './Reviews';
export { default as Footer } from './Footer';
export {default as Home } from './Home';
export {default as AllProducts} from './AllProducts';
export {default as About } from './About';
export {default as Contact} from './Contact';
export {default as Account } from './Account';
